name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --prefix=$(pwd)/install
    - name: Install dependencies
      run: make
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: linux.zip
        path: ./install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: linux.zip
        path: linux.zip
